all:
	gcc -o sum-big sum-big.c list.c
	gcc -o mult-big mult-big.c list.c
	gcc -o test-list test-list.c list.c
	gcc -o test-remove-k test-remove-k.c list.c
clean:
	rm sum-big mult-big test-list test-remove-k
