all:
	gcc -o bubble bubble.c utils.c
	gcc -o selection selection.c utils.c
	gcc -o bubble-rec bubble-rec.c utils.c
	gcc -o selection-rec selection-rec.c utils.c
	gcc -o bubble-birecional bubble-birecional.c utils.c
clean:
	rm bubble selection bubble-rec selection-rec bubble-birecional 
